#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-debugme
Version  : 1.2.0
Release  : 51
URL      : https://cran.r-project.org/src/contrib/debugme_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/debugme_1.2.0.tar.gz
Summary  : Debug R Packages
Group    : Development/Tools
License  : MIT
Requires: R-crayon
BuildRequires : R-crayon
BuildRequires : R-mockery
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
control debugging of packages via environment variables.

%prep
%setup -q -n debugme
pushd ..
cp -a debugme buildavx2
popd
pushd ..
cp -a debugme buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1714064386

%install
export SOURCE_DATE_EPOCH=1714064386
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/debugme/DESCRIPTION
/usr/lib64/R/library/debugme/INDEX
/usr/lib64/R/library/debugme/LICENSE
/usr/lib64/R/library/debugme/Meta/Rd.rds
/usr/lib64/R/library/debugme/Meta/features.rds
/usr/lib64/R/library/debugme/Meta/hsearch.rds
/usr/lib64/R/library/debugme/Meta/links.rds
/usr/lib64/R/library/debugme/Meta/nsInfo.rds
/usr/lib64/R/library/debugme/Meta/package.rds
/usr/lib64/R/library/debugme/NAMESPACE
/usr/lib64/R/library/debugme/NEWS.md
/usr/lib64/R/library/debugme/R/debugme
/usr/lib64/R/library/debugme/R/debugme.rdb
/usr/lib64/R/library/debugme/R/debugme.rdx
/usr/lib64/R/library/debugme/help/AnIndex
/usr/lib64/R/library/debugme/help/aliases.rds
/usr/lib64/R/library/debugme/help/debugme.rdb
/usr/lib64/R/library/debugme/help/debugme.rdx
/usr/lib64/R/library/debugme/help/paths.rds
/usr/lib64/R/library/debugme/html/00Index.html
/usr/lib64/R/library/debugme/html/R.css
/usr/lib64/R/library/debugme/tests/testthat.R
/usr/lib64/R/library/debugme/tests/testthat/test-colors.R
/usr/lib64/R/library/debugme/tests/testthat/test-debug.R
/usr/lib64/R/library/debugme/tests/testthat/test-dynamic.R
/usr/lib64/R/library/debugme/tests/testthat/test-instrument.R
/usr/lib64/R/library/debugme/tests/testthat/test-levels.R
/usr/lib64/R/library/debugme/tests/testthat/test-package.R
